/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 gasMask.gltf 
Author: TM05 (https://sketchfab.com/TM05)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gas-mask-0565218a14114608b5e58c54de321fa4
Title: Gas Mask
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function GasMask(props) {
  const { nodes, materials } = useGLTF("/gasMask.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.low_helmet_mat_0.geometry}
            material={materials.helmet_mat}
          />
          <mesh
            geometry={nodes.low_helmet_mat_0_1.geometry}
            material={materials.helmet_mat}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/gasMask.gltf");
